#! /bin/sh

#wmname LG3D &
#vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &


# Dunst
dunst -conf ~/.config/dunst/dunstrc &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a org.gnome.Nautilus state=floating

# RESOLUCION ARANDR
xrandr -s 1920x1080

#Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# WALLPAPER
feh --bg-fill ~/Wallpaper/tron_legacy1.jpg

# POLYBAR
~/.config/polybar/launch.sh

# CUSTOM
bspc config focus_follows_pointer true

# PICOM
picom &
bspc config border_width 0

xsetroot -cursor_name left_ptr &

setxkbmap latam 

