#!/bin/bash


rofi_command="rofi -theme ~/.config/polybar/scripts/themes/powermenu_alt.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=" Apagar"
reboot=" Reiniciar"
lock=" Bloquear"
suspend=" Suspender"
logout=" Cerrar Sesión"

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "System" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        i3lock
        ;;
    $suspend)
        systemctl suspend
        ;;
    $logout)
        kill -9 -1
        ;;
esac





